version: "3.8"

services:
  helia-ipfs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/ipfs-blockstore
    environment:
      - FRONTEND_URL=http://localhost:3000
      - NODE_ENV=production
      - PORT=5001
    restart: unless-stopped
